### ISSUE TITLE
Switch Procon Support

### ISSUE THREAD

**Issue by LuigisMansion** [msxmine/SI2DSU#1]
I've tested this tool with the switch pro controller and it does indeed read switch controller motion data but any tiny movement makes the gyro go crazy. I skimmed over the source and saw that the values for motion movement on the other controllers are divided by large constants. Are these values unknown for the Switch controller?

**Comment by msxmine** [comment]
The multipliers are the same as DS4, what is unknown is the XYZ mapping and polarity (Which way is positive/negative). If you want to help, get [this debug build](https://github.com/msxmine/SI2DSU/releases/download/0.1/debug.zip) . It will show the values it gets from steam in a terminal window. Then, figure out which of the displayed numbers corresponds to which axis on the reference image below (and if the direction with pointing arrows yields positive numbers) . The gyro will only respond to rotational movement, but the accelerometer will show a combined value near 16384 with the controller laying still, because it also detects gravity.
![dsrotations](https://user-images.githubusercontent.com/4729023/93318786-61f70d00-f80f-11ea-87e3-bf291333bd7b.png)

**Comment by msxmine** [comment]
Fixed in release 0.2
